### ISSUE TITLE
As a traffic manager, I would like to check A22 traffic data in testing environment (put A22 Traffic DC developed by 1006.org in testing environment)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#15]
- [ ] Chris provides the source code of the first DC
- [ ] @bertolla implements the pipeline

We have to wait till Chris pushes the complete source code for version 0.1

**Comment by chris-mair** [comment]
Uhm, I just now see this from 2018...

The A22 traffic data is different from everything else, because it is large data stream that has its own special collector that runs standalone and feeds into a dedicated db (a22db).

I don't think this could or should be integrated into a test environment I don't see the point (and expenses) to double this infrastructure (a dedicate Beanstalk instance with at least 8 GB RAM and a few hundered GB of RDS...).

@rcavaliere I suggest closing this.

Bye,
Chris.
