### ISSUE TITLE
As an end-user I would like to get fresh travel A22 times data from the Open Data Hub

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#229]
The Data Collector was blocked since the source has started to send '0' for some coordinates, which throws an exception and blocks the Data Collector

To do:
- [x] investigate problem by @bertolla 
- [x] document problem by @bertolla 
- [x] share information with Catch & Solve by @rcavaliere 
- [x] increase data quality with A22 by @rcavaliere 
- [x] solve issue by Catch & Solve (code should be robust to these cases)

**Comment by bertolla** [comment]
I sent you this link where the exception is thrown:
https://github.com/noi-techpark/bdp-commons/blob/360020c3f26d4bc645853dda73dfc057e039443f/data-collectors/traveltimes-a22/src/main/java/it/bz/noi/a22/traveltimes/Connector.java#L220

and the issue is "When parsing a coordinate which has 0 as value to a Double there will be an Exception since 0 is no valid double"
