### ISSUE TITLE
As a project manager I would like that the hubs of the new car pooling service under implementation are read from a shared Google Sheet file

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#282]
There is a completely new car pooling service coming to South Tyrol, which can be disruptive: it's called ummadum: https://ummadum.com/

Similarly to the existing car pooling service, it will also be characterized by "hubs", i.e. predefined destinations where users can more easily decide to end a joint trip. Differently from today, hubs are going to be managed in a shared Google Sheet file available there: https://docs.google.com/spreadsheets/d/1K49hBRbloKMtwxqBPHMf8yVFsu1xjFtUfk4CVtZhTMI/edit?usp=sharing

These hubs are going to be managed by local organizations / partners. The ummadum system will read the data from the ODH and integrate the hubs as possible destinations. 

Through other user stories we will then cover the implementation of a specific new Data Collector to get the information from the ummadum system

**Comment by bertolla** [comment]
@rcavaliere 
Why is it an enhancement?

I had to rename the `name` fields of the spreadsheet since they did not follow the naming conventions that our spreadsheets reader is following. For each hub I create in the odh, I need a unique identifier which should be defined in the sheet. We can either ...
- use one of the existing fields
- create a custom field in the spreadsheet
- combine multiple existing fields to create it

**Comment by rcavaliere** [comment]
@bertolla the Google Sheet was created by me, you can configure it in the best way you thing it is useful for the integration in the Open Data Hub. For the IDs, of course we can create a column for that and define a convention for this. Let me think about this a little bit..

**Comment by bertolla** [comment]
@rcavaliere Have you thought about it, I just need that information to to to testing

**Comment by rcavaliere** [comment]
@bertolla you are right. Maybe for the start we can create a custom field and use a convention like "HUB_nr" and we give a progressive number to the hubs we create them (e.g. HUB_1, HUB_2, etc.). We should also have a field called "status" to use in case we want to deactivate hubs: I would avoid to delete rows from the sheet, but rather set them as "NOT_ACTIVE" (default value could be "ACTIVE"). What do you think about this proposal?

**Comment by bertolla** [comment]
CarpoolingHubs are now visible in the test db and I guess also on analytics.
I'm currently doing a backup and restore on the database so they might not be visible after the restore.

**Comment by rcavaliere** [comment]
I see the data in the test DB. I see something strange for stationcode and origin, what did you put for these fields?

**Comment by rcavaliere** [comment]
@bertolla will add a field alternative to the origin so to let a 3rd party understand who is data provider.
For the stationcode please use the namespace: "ummadum:" + the unique number

**Comment by bertolla** [comment]
I checked again, this is not doable using the current google spreadsheet data-collector.
It should not be of any concern since it is a unique id and holds no information aggregated with the dataprovider.
This is an example query which does not return stationcode and it still works:
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/CarpoolingHub/?select=scoordinate,smetadata&where=sorigin.eq.%221K49hBRbloKMtwxqBPHMf8yVFsu1xjFtUfk4CVtZhTMI%22,sactive.eq.true
If you want to pretify the query without using the origin you can just add a field in the spreadsheet and filter by that and the query could look like this
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/CarpoolingHub/?select=scoordinate,smetadata&where=smetadata.origin.eq.ummadum,sactive.eq.true

**Comment by rcavaliere** [comment]
In this case I would suggest to add an additional field in the Google Sheet for the stationcode. Would this be feasible and OK for you?

**Comment by bertolla** [comment]
Well you can add a field but it will not be exposed as stationcode, but as smetadata.stationcode. You can define that as you want.

**Comment by rcavaliere** [comment]
@bertolla I added a new field called origin, so to keep trace about how is the "owner" of a certain hub. This should be useful to manage the list and also for the above filtering needs

**Comment by rcavaliere** [comment]
@bertolla I don't see the field "origin" in the JSON stored in the metadata. Do you need to add something in the Data collector logic?

**Comment by bertolla** [comment]
I had to trigger a sync manually since I don't have google send change notifications on our test environment.
Now it's visible:
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/CarpoolingHub/?select=scoordinate,smetadata&where=smetadata.origin.eq.BZBGA,sactive.eq.true

**Comment by bertolla** [comment]
This is only running on test. Don't you want me to put it to production?

**Comment by bertolla** [comment]
@rcavaliere Can you give me write access to the google spreadsheet, so I can test the triggering of the sync?

**Comment by rcavaliere** [comment]
@bertolla done!
