### ISSUE TITLE
APPATN Environmental DC raw measurement can be put in stand-by

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#512]
As the measurement station has been put in stand-by, we can temporarily stop this DC: https://github.com/noi-techpark/bdp-commons/tree/main/data-collectors/environment-appa-tn-tenminutes

**Comment by Piiit** [comment]
@dulvui If you put it in standby, we need also an upgrade of the alert and dashboard rules https://github.com/noi-techpark/infrastructure/blob/main/grafana/config.js

I think we can comment that block and then remove it manually from Grafana. I need to see... I will do this, since all these alerts are still in testing

**Comment by dulvui** [comment]
DC deployment is stopped and commented out in the Github Action.
Also the Grafana dashboard for this DC has been commented out in the config and removed.
