### ISSUE TITLE
As a Data Consumer I would like that the VMS data of Autobrennero is much more "real-time"

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#568]

**Comment by dulvui** [comment]
I increased now the maximum RAM limit, because currently it ran out of memory after some time.
Now the data-collector is working again and synced with the latest data.
I will still investigate the problem and try to optimize the import to make it more "real time".

**Comment by rcavaliere** [comment]
@dulvui thanks for your effort. I see now that the data are updated to yesterday morning. To have still further issues in following the data stream?

**Comment by dulvui** [comment]
The is still the problem that it takes around 24 hours to do the import and since now it had to import data of a whole week it took even more. Now it should update every ~24 hours but I'll check out the code to see how to make it more "real time" by optimizing the API calls.

**Comment by dulvui** [comment]
@rcavaliere The data collector takes now less than 20 minutes to make a full import :rocket: 
For now it is only in testing. I will see if everything works and put to production next week.

**Comment by dulvui** [comment]
@rcavaliere There is now a problem with the active stations. Currently on testing there are much less active stations than in production, because since now the data collector runs circa every 25 minutes instead of every 24 hours and only the signs that had data the last 25 minutes are set to active, all the other signs have active false.
Let's check together in the office if this actually is a problem and in case I can increase the scan window.

**Comment by rcavaliere** [comment]
@dulvui yes it is a problem, we should avoid that a VMS that does not have an update is set to active = false. Can we decouple the fact that we have real-time data with the update of the status of the station?

**Comment by dulvui** [comment]
@rcavaliere Yes we can. The status change happens when a sync station is called and a station is no longer in the list, then it gets the field active = false. Currently the station sync and the data push happens in the same call every 25 minutes, so just a few stations are synced and all the others are active = false.
I could modify it so that the data push remains the same every 25 minutes and the station sync happens only every 24 hours (?) or so.
Would 24 hours be fine or should I put even more?

**Comment by dulvui** [comment]
@rcavaliere Its now live in production and working fine
