### ISSUE TITLE
As STA I would like to have also the bike parking locations as Open Data Hub stations, since it could be useful to provide directly some real-time information also associated a group of bike parking stations that are physically connected

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#614]
The Bike Parking STA Data Collector should be extended as indicated in the technical specification annexed. At the end we should just create a new station type, all the rest remains as it is.

[230811_SpecificheIntegrazione_NOI_v3.1-clean.pdf](https://github.com/noi-techpark/bdp-commons/files/12319062/230811_SpecificheIntegrazione_NOI_v3.1-clean.pdf)

**Comment by clezag** [comment]
Ciao Roberto,

mi sono accorto che attualmente il station name della BikeParking station viene settato col valore di "locationName", invece di "name", come definito nel documento.
Mi sa che questa era una delle tematiche nello scambio mail.

Il campo "name" però è troppo generico, tipo "Bike depot", o "Individual Box".
Cosa ne dici se facciamo lo station name "locationName / name" ?

```
Bressanone/Brixen, Bressanone/Brixen train station / Bike depot
Bressanone/Brixen, Bressanone/Brixen train station / Individual Box
```
La BikeParkingBay poi eredita il nome ed aggiunge la posizione 

Nei metadata ci sarà pure la mappa con tuttel le traduzioni del "name" provveniente dall'API come da specifiche.

**Comment by rcavaliere** [comment]
@clezag per me va bene!

**Comment by clezag** [comment]
@rcavaliere The changes are now up in testing.
Some details that vary from the specification document:
- station and bay names now are composed of "Location / Station / Bay" names, where previously they were "Location / Bay"
- data types are named slightly differently (freeSpotsRegularBike, freeSpotsElectricBike)

I've also fixed the colors and data types in analytics and opened the new station type in the API.

Since the location is not visible in analytics, this URL can be used to query the location data:
```
https://mobility.api.opendatahub.testingmachine.eu/v2/flat%2Cnode/BikeParkingLocation/%2A/latest
```

I've noticed that it could be useful adding up the totalPlaces of stations and adding that to location metadata, as this would compliment the "free" data we already sum up.

**Comment by rcavaliere** [comment]
@clezag perfect, everything looks fine! Yes, you are right, totalPlaces could be useful to be added as metadata to the bike parking location stations. Please do it! Once done, we can put this new version of Data Collector in production

**Comment by clezag** [comment]
@rcavaliere I've released the changes in production.

For some reason, analytics does not correctly display the green/red/yellow color indicator.
Analytics has a ton of changes related to events that cannot yet go into production, I think once that gets deployed, the colors for bike parking should be displayed correctly.
