### ISSUE TITLE
As Smart Taxi Merano I would like to integrate the real-time information of my taxi services in the Open Data Hub, so that I can be integrated in 3rd parties applications

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#675]
- [x] Specifications of the modalities of integration, based on the API provided
- [x] Data Collector implementation

Proposed specifications on how to integrate the available data:

[240905_SpecificheIntegrazione_NOI_v1.1.docx](https://github.com/user-attachments/files/16883792/240905_SpecificheIntegrazione_NOI_v1.1.docx)

**Comment by rcavaliere** [comment]
@dulvui @clezag this Data Collector is now ready to be implemented. Actually should be very easy to implement. Do we want to implement this directly in the new infrastructure?

**Comment by clezag** [comment]
@rcavaliere 
Yes, from here on out everything new will be implemented on the new infrastructure.

This issue also looks ideal to get @LuhoDaan started on the time series domain and the new infrastructure, so barring any particular urgency, I would assign it to him.

@dulvui told me we are only allowed to save the raw data of whitelisted Taxi Drivers. Is this a hard requirement? It would run counter to the new infrastructure's principles (don't modify the raw data at collector stage) and we would have to do a custom implementation instead of being able to reuse an existing data collector component.

Ideally, the whitelist would filter later, in the transformer, so still only whitelisted drivers will be published on the Open Data Hub. Nobody external will be able to access the raw data.

**Comment by rcavaliere** [comment]
@clezag for me it is OK if @LuhoDaan make this implementation! It's simple and therefore a good exercise for him.
For the data retrieval: formally we couldn't store the data of taxi drivers that do not want to share their data. However, we could apply this "white-list" filter at the level of integration in the structured DB.

**Comment by rcavaliere** [comment]
@clezag @LuhoDaan proposal is to set the polling time to 1 minute. Then let's if it is worth to change this.

**Comment by luhodaan** [comment]
@rcavaliere 
The data collector has been completed and deployed in the test environment. Once I'll receive the whitelist, it will be used to filter the data that can be published in production in compliance with the integration guidelines.

**Comment by rcavaliere** [comment]
@luhodaan wonderful, looking forward to test this! The following taxis should be put in whitelist: 5,6,9, 28, 29.

**Comment by rcavaliere** [comment]
@luhodaan where did you deploy the data collector? I don't see taxi data in the testing environment...

**Comment by rcavaliere** [comment]
@luhodaan @clezag the Data Collector looks fine to me. However I would suggest following fix:
-  [ ] shouldn't we put the coordinates also in the station table, so that we can easily visualize taxis? Otherwise a Data Consumer has to check the measurements for this. But maybe writing highly dynamic data in the station table is not a good idea...
- [ ] I think that at present we don't store the measurement 'state' as measurement, right? Can you please add this.

**Comment by clezag** [comment]
@rcavaliere I agree having stations update that often is not ideal, but not having any location there will be even more confusing to users. 
If we want to always put the most recent location also at station level, we can do that, I don't think there is currently any technical reason not to do it. It just makes future implementations more tricky when talking about caching etc., because now stations have to be considered "real time" where previously they were fairly static.

An alternativ I've thought about could be setting a GPS location of where a taxi driver has his "home base", like I know in Merano they usually idle in Via Carducci(Piazza Teatro) or Piazza della Rena, so it could be the location where they can be found if not on a trip, or just put the center of Merano for every taxi.
This would be better for search, because when you want to get a list of taxi drivers of Merano, if one of the vehicles is out on a trip (let's say they drove someone to Val Venosta) they will not appear on the search until they return.

The main issue would be communicating this to users, so they know to check the live location in measurements as well if they need it, and not the static one. 
Another is the map you've talked about: Our tooling (analytics) currently does not support getting location from measurements, so for these taxis it would not show the live location if we don't have it in the station gps point.

**Comment by rcavaliere** [comment]
@clezag in this case it's better to leave the positions empty, otherwise we provide a wrong information. Then it should be the front-end application knowing that the position is provided in this case as data, not as metadata.

**Comment by clezag** [comment]
I still think having some position there would be good, because all our geo filters will not work on the measurements (as it's just a json with lat and long field, not really a gps point). 
Request like "get all taxis in south tyrol" will not be possible with the standard API tools, and any generic tool that's developed will not be able to display them on a map.

While I don't think having the real time location in the station is ideal, I would prefer that over having nothing.

**Comment by luhodaan** [comment]
@rcavaliere @clezag I see the points, it seems to me that state is pushed in the measurementstring table under string value, but I'll check again, since maybe some values might be missing. 

About the update of station coordinates at the moment it does it with the same frequency as it does for measurement, so I'm up for any necessary changes.

Another quick point is about the whitelist; from the [240905_SpecificheIntegrazione_NOI_v1.1.docx](https://github.com/user-attachments/files/16883792/240905_SpecificheIntegrazione_NOI_v1.1.docx) it seems that we should filter based on IdUtente which is a 4 digit number, while on the recent whitelist I see that they're 1 or 2 digit numbers, should I filter based on the last two char of the Nickname instead which looks more similar to the provided whitelist?

**Comment by rcavaliere** [comment]
@luhodaan yes you are right, it's not clear. But I see that on the provided external API at present we just receive 5 records, 1 per taxi, which should be exactly the taxis providing the data. But let me me check with the Data Provider, in the meantime leave as you implemented.

**Comment by rcavaliere** [comment]
@luhodaan finally we got the list of IdUtente to be put in the white list: 2343, 2344,2345, 2350, 2764

**Comment by rcavaliere** [comment]
@luhodaan @clezag I would suggest to reuse as station type name `ON_DEMAND_VEHICLE`, which is already in use, so to avoid to create a new data type. Testing again the data we are importing, it seems to me that we don't have collect measurements associated to the type `state`, can you check?

**Comment by luhodaan** [comment]
@rcavaliere about the station type name, what about something more explicit such as `Taxi` ? After talking with @clezag it seems that adding a new station type name to the ninja isn't that much extra work, and it would follow the current convention of having the station type names in CamelCase. What do you think about it ?

About the `state`, I've double checked and yes we do collect them, under measurementstring.string_value you can find the measurement states for the taxis and they're associated with the type ids that have as type cname `state`.

**Comment by rcavaliere** [comment]
@luhodaan it's not that kind of impact, but the advantage is that we could have with a simple API call both taxis and on-demand vehicles, which would be very appreciated. OK for the data type `state`, just checked!

**Comment by luhodaan** [comment]
@rcavaliere ok that is fine for me, I've just updated the station type name to `ON_DEMAND_VEHICLE` and completed the deploy in testing.
After some other checks I'll move to production.

**Comment by rcavaliere** [comment]
@luhodaan wonderful! In this way the data will be immediately visible e.g. on mobility.meran.eu. Let's go in production!
